image: docker:latest
services:
  - docker:dind
variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci
stages:
  - build
  - test
  - package
  - deploy
maven-build:
  image: maven:3-openjdk-18
  stage: build
  script: "mvn package -B"
  artifacts:
    paths:
      - target/*.jar
docker-build:
  stage: package
  script:
  - docker login -u $DOCKER_USERNAME --password ${DOCKER_PASSWORD}
  - docker build -t ${DOCKER_USERNAME}/backend:$CI_COMMIT_SHORT_SHA .
  - docker push ${DOCKER_USERNAME}/backend:$CI_COMMIT_SHORT_SHA
