name: CI

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: winniemonel

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:dind
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build with Maven
        run: mvn package -B
        continue-on-error: true
        id: build
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jar
          path: target/*.jar
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: winniemonel/backend:${{ github.sha }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        if: steps.build.outcome == 'success'
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: |
          docker build -t winniemonel/backend:${{ github.sha }} .
        env:
          DOCKER_USERNAME: ${{ env.DOCKER_USERNAME }}
      - name: Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: winniemonel/backend:${{ github.sha }}
        env:
          DOCKER_USERNAME: ${{ env.DOCKER_USERNAME }}
        if: success()